# Generated by Django 5.0.6 on 2024-09-28 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_loginhistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoginHistory',
        ),
    ]
